mlops:
  project_name: "Speaking Fridgey"
  experiment_name: "mlflow test"
  run_name: "jihye"
  user_name: "jihye"
  host: "http://localhost:8080/api/v1"
  username: "airflow"
  password: "airflow"
  system_tags: "v1"