model_configuration:
  mode: 0
  model_name: !!str ctpn
  pretrained_model: !!str '/home/ubuntu/user/jihye.lee/ocr_exp_v1/text_detection/weight/ctpn.pth'
  params:
    ch_in: !!int 3
    branch_name: !!str "vgg16_bn"
    geo_type: !!str "rbox"
    output_scope: !!int 1024
    pretrained_bbone: !!bool True
    freeze_bbone: !!bool True

data_configuration:
  label_path: !!str "/home/ubuntu/user/jihye.lee/data/new_box_data.zip"
  img_path: 
    - "image_data-20221112T142753Z-001.zip" 
    - "image_data-20221112T142753Z-002.zip"
    - "image_data-20221112T142753Z-003.zip" 
    - "image_data-20221112T142753Z-004.zip" 
    - "image_data-20221112T142753Z-005.zip" 
    - "image_data-20221112T142753Z-006.zip" 
    - "image_data-20221112T142753Z-007.zip" 
    - "image_data-20221112T142753Z-008.zip" 
    - "image_data-20221112T142753Z-009.zip" 
    - "image_data-20221112T142753Z-010.zip" 
    - "image_data-20221112T142753Z-011.zip" 
    - "image_data-20221112T142753Z-012.zip" 
    - "image_data-20221112T142753Z-013.zip"  # "/home/ubuntu/user/jihye.lee/data/detection_aihub/image_data.zip"
  train_data_path: !!str ""
  eval_data_path: !!str ""
  batch_size: !!int 2
  scale: !!float 0.25
  crop_length: !!int 800
  # eval_crop_length: !!int 512
  mean: !!float 0.5
  std: !!float 0.5
  

train_configuration:
  epoch: !!int 30
  eval_epoch: !!int 2
  eval_weight: !!str "/home/ubuntu/user/jihye.lee/ocr_exp_v1/text_detection/results"
  learning_rate: !!float 1e-3
  optimizer: !!str "adam"
  weight_decay: !!float 1e-5
  scheduler: !!str "warm up"
  criterion: 
    loss: !!str "ctpnloss"
    lamda: !!float 1.0


eval_configuration:
  weight: !!str "/home/ubuntu/user/jihye.lee/ocr_exp_v1/text_detection/results"
  epoch: !!int 10

mlops_configuration:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "Speaking Fridgey: Text Detection"
  run_name: "text detection test [CTPN]"
  user_name: "jihye.lee"
