model_configuration:
  mode: 0
  model_name: !!str east
  pretrained_model: !!str ''
  params:
    ch_in: !!int 3
    branch_name: !!str "vgg19_bn"
    geo_type: !!str "rbox"
    output_scope: !!int 1024
    pretrained_bbone: !!bool True
    freeze_bbone: !!bool True

data_configuration:
  label_path: !!str "/home/ubuntu/user/jihye.lee/data/detection_aihub/box_data.zip"
  img_path: !!str "/home/ubuntu/user/jihye.lee/data/detection_aihub/image_data-20221112T142753Z-001.zip" # "/home/ubuntu/user/jihye.lee/data/detection_aihub/image_data.zip"
  train_data_path: !!str ""
  eval_data_path: !!str ""
  batch_size: !!int 4
  scale: !!float 0.25
  crop_length: !!int 1024
  # eval_crop_length: !!int 512
  mean: !!float 0.5
  std: !!float 0.5
  

train_configuration:
  epoch: !!int 20
  eval_epoch: !!int 5
  learning_rate: !!float 2e-4
  optimizer: !!str "adam"
  weight_decay: !!float 1e-5
  scheduler: !!str "warm up"
  criterion: 
    loss: !!str "eastloss"
    lamda: !!float 1.0


eval_configuration:
  weight: !!str "/home/ubuntu/user/jihye.lee/ocr_exp_v1/text_detection/results"
  epoch: !!int 10

mlops_configuration:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "Speaking Fridgey: Text Detection"
  run_name: "text detection test"
  user_name: "jihye.lee"
